[build]
publish = "single-spa/page-root-config/dist"
edge_functions = "single-spa/page-root-config/custom-edge-functions-dir"

[functions]
directory = "single-spa/page-root-config/my_functions"

# An example local build plugin
[[plugins]]
package = "single-spa/page-root-config/custom-build-plugin"